### ISSUE TITLE
加载模型出现json错误

### ISSUE THREAD

**Issue by mst272** [deepseek-ai/DeepSeek-Coder#100]
报错如下，这是什么原因嘞

> Traceback (most recent call last):
  File "/home/jtuser/work/DeepSeek-Coder/finetune/finetune_deepseekcoder.py", line 193, in <module>
    train()
  File "/home/jtuser/work/DeepSeek-Coder/finetune/finetune_deepseekcoder.py", line 144, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/home/jtuser/.local/conda/envs/codellm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/home/jtuser/.local/conda/envs/codellm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3351, in from_pretrained
    resolved_archive_file, sharded_metadata = get_checkpoint_shard_files(
  File "/home/jtuser/.local/conda/envs/codellm/lib/python3.9/site-packages/transformers/utils/hub.py", line 994, in get_checkpoint_shard_files
    index = json.loads(f.read())
  File "/home/jtuser/.local/conda/envs/codellm/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/jtuser/.local/conda/envs/codellm/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jtuser/.local/conda/envs/codellm/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mst272** [comment]
已解决，是模型出现了错误

**Comment by ANHDY** [comment]
> 已解决，是模型出现了错误

你好，想问一下是如何解决的？现在调用deep seek- v3模型也会出现该问题

**Comment by mckay-w** [comment]
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model='deepseek-reasoner',
    openai_api_key='sk-xxx', 
    openai_api_base='https://api.deepseek.com',
    max_tokens=1024
)

response = llm.invoke("给我一个很土但是听起来很好养活的男孩小名 ", temperature=1)

#print(response.reasoning_content)
print(response.content)

我调用 reasoner 也报错 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/mckay/test/test_deepseek.py", line 6, in <module>
    response = client.chat.completions.create(
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 815, in create
    return self._post(
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/site-packages/openai/_base_client.py", line 1060, in _request
    return self._process_response(
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/site-packages/openai/_base_client.py", line 1159, in _process_response
    return api_response.parse()
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/site-packages/openai/_response.py", line 317, in parse
    parsed = self._parse(to=to)
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/site-packages/openai/_response.py", line 259, in _parse
    data = response.json()
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/mckay/anaconda3/envs/myenv/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mst272** [comment]
> > 已解决，是模型出现了错误
> 
> 你好，想问一下是如何解决的？现在调用deep seek- v3模型也会出现该问题

时间有点久了  好像是因为模型下载出现了错误，重新下载试一下吧
