### ISSUE TITLE
不能把模型转化为gguf

### ISSUE THREAD

**Issue by dotyuu** [deepseek-ai/DeepSeek-Coder#98]
python D:\Ai\convert.py D:\Ai\deepseek-coder-6.7b-instruct
D:\Ai\gguf-py
Loading model file D:\Ai\deepseek-coder-6.7b-instruct\pytorch_model-00001-of-00002.bin
Loading model file D:\Ai\deepseek-coder-6.7b-instruct\pytorch_model-00001-of-00002.bin
Loading model file D:\Ai\deepseek-coder-6.7b-instruct\pytorch_model-00002-of-00002.bin
params = Params(n_vocab=32256, n_embd=4096, n_layer=32, n_ctx=16384, n_ff=11008, n_head=32, n_head_kv=32, f_norm_eps=1e-06, n_experts=None, n_experts_used=None, rope_scaling_type=<RopeScalingType.LINEAR: 'linear'>, f_rope_freq_base=100000, f_rope_scale=4.0, n_orig_ctx=None, rope_finetuned=None, ftype=None, path_model=WindowsPath('D:/Ai/deepseek-coder-6.7b-instruct'))
Traceback (most recent call last):
  File "D:\Ai\convert.py", line 1658, in <module>
    main(sys.argv[1:])  # Exclude the first element (script name) from sys.argv
    ^^^^^^^^^^^^^^^^^^
  File "D:\Ai\convert.py", line 1614, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type, model_parent_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\convert.py", line 1409, in load_vocab
    path = self._select_file(vocabtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\convert.py", line 1384, in _select_file
    raise FileNotFoundError(f"{vocabtype} {file_key} not found.")
FileNotFoundError: spm tokenizer.model not found.

**Comment by guoday** [comment]
这里有人转化了
https://huggingface.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF
